---

- name: Create Tenant
  hosts: campus
  serial: True
  vars:
    now_time: "{{ansible_date_time.date}} {{ansible_date_time.time}}"
  tasks:  
    - name: Create tenant "{{tenant_name}}"
      tags: create_tenant
      vars:
        tenant_info:
          tenantName: "tenantabcd123456"
          userAccount: "tenantabcd123456"
          userPassword: "123456ABcd!"
        tenant_infos:
          tenant: ["{{tenant_info}}"]
      uri:
        url: 'https://{{north_ip}}:{{north_port}}/controller/campus/v1/baseservice/tenants'
        method: POST
        body: '{{tenant_infos}}'
        body_format: json
        validate_certs: False
        return_content: yes
        headers:
          X-ACCESS-TOKEN: "{{lookup('file','/tmp/ansible-temp')}}"
          Accept: application/json
          Content_Type: application/json
        status_code: 204
      register: tenant_result
    - name: response from create tenant
      debug:
        msg: "{{tenant_result}}"
