---

- name: Update Tenant
  hosts: campus
  serial: True
  vars:
    now_time: "{{ansible_date_time.date}} {{ansible_date_time.time}}"
  vars_prompt:
    - name: "tenant_id"
      prompt: "Please input the tenant id that you want to update "
      private: no
    - name: "tenant_name"
      prompt: "Please input tenant name "
      private: no
    - name: "tenant_desc"
      prompt: "Please input tenant description "
      private: no
  tasks:
    - name: check tenant_id is null
      fail:
        msg: "Update Tenant fail! tenant_id is null"
      when: tenant_id == ''
    - name: check tenant_name is null
      fail:
        msg: "Update Tenant fail! tenant_name is null"
      when: tenant_name == ''
    - name: Update tenant "{{tenant_id}}"
      tags: update_tenant
      vars:
        tenant_info:
          id: "{{tenant_id}}"
          name: "{{tenant_name}}"
          description: "{{tenant_desc}}"
          updateAt: "{{now_time}}"
        tenant_infos:
          tenant: ["{{tenant_info}}"]
      uri:
        url: 'https://{{north_ip}}:{{north_port}}/controller/campus/v2/baseservice/tenants'
        method: PUT
        body: '{{tenant_infos}}'
        body_format: json
        validate_certs: False
        return_content: yes
        headers:
          X-ACCESS-TOKEN: "{{lookup('file','/tmp/ansible-temp')}}"
          Accept: application/json
          Content_Type: application/json
        status_code: 200
      register: tenant_result
      ignore_errors: yes
    - name: response from update a tenant
      debug:
        msg: "{{tenant_result}}"
